offset_size: 4
mfg_offsets:
  SID_PAL_MFG_STORE_MAGIC:
    start: 0
    end: 1
  SID_PAL_MFG_STORE_VERSION:
    start: 1
    end: 2
  SID_PAL_MFG_STORE_SERIAL_NUM:
    null
  SID_PAL_MFG_STORE_SMSN:
    null
  SID_PAL_MFG_STORE_APID:
    null
  SID_PAL_MFG_STORE_APP_PUB_ED25519:
    null
  SID_PAL_MFG_STORE_DEVICE_PRIV_ED25519:
    null
  SID_PAL_MFG_STORE_DEVICE_PUB_ED25519:
    null
  SID_PAL_MFG_STORE_DEVICE_PUB_ED25519_SIGNATURE:
    null
  SID_PAL_MFG_STORE_DEVICE_PRIV_P256R1:
    null
  SID_PAL_MFG_STORE_DEVICE_PUB_P256R1:
    null
  SID_PAL_MFG_STORE_DEVICE_PUB_P256R1_SIGNATURE:
    null
  SID_PAL_MFG_STORE_DAK_PUB_ED25519:
    null
  SID_PAL_MFG_STORE_DAK_PUB_ED25519_SIGNATURE:
    null
  SID_PAL_MFG_STORE_DAK_ED25519_SERIAL:
    null
  SID_PAL_MFG_STORE_DAK_PUB_P256R1:
    null
  SID_PAL_MFG_STORE_DAK_PUB_P256R1_SIGNATURE:
    null
  SID_PAL_MFG_STORE_DAK_P256R1_SERIAL:
    null
  SID_PAL_MFG_STORE_PRODUCT_PUB_ED25519:
    null
  SID_PAL_MFG_STORE_PRODUCT_PUB_ED25519_SIGNATURE:
    null
  SID_PAL_MFG_STORE_PRODUCT_ED25519_SERIAL:
    null
  SID_PAL_MFG_STORE_PRODUCT_PUB_P256R1:
    null
  SID_PAL_MFG_STORE_PRODUCT_PUB_P256R1_SIGNATURE:
    null
  SID_PAL_MFG_STORE_PRODUCT_P256R1_SERIAL:
    null
  SID_PAL_MFG_STORE_MAN_PUB_ED25519:
    null
  SID_PAL_MFG_STORE_MAN_PUB_ED25519_SIGNATURE:
    null
  SID_PAL_MFG_STORE_MAN_ED25519_SERIAL:
    null
  SID_PAL_MFG_STORE_MAN_PUB_P256R1:
    null
  SID_PAL_MFG_STORE_MAN_PUB_P256R1_SIGNATURE:
    null
  SID_PAL_MFG_STORE_MAN_P256R1_SERIAL:
    null
  SID_PAL_MFG_STORE_SW_PUB_ED25519:
    null
  SID_PAL_MFG_STORE_SW_PUB_ED25519_SIGNATURE:
    null
  SID_PAL_MFG_STORE_SW_ED25519_SERIAL:
    null
  SID_PAL_MFG_STORE_SW_PUB_P256R1:
    null
  SID_PAL_MFG_STORE_SW_PUB_P256R1_SIGNATURE:
    null
  SID_PAL_MFG_STORE_SW_P256R1_SERIAL:
    null
  SID_PAL_MFG_STORE_AMZN_PUB_ED25519:
    null
  SID_PAL_MFG_STORE_AMZN_PUB_P256R1:
    null
