name: Build Sidewalk samples and tests
on:
  workflow_call:
    inputs:
      change_nrf_revision:
        description: 'change revision of nrf in west.yml to `main`'
        required: false
        type: boolean
        default: false

jobs:
  run_dut_ut:
    runs-on: test-node
    container:
      image: ghcr.io/nrfconnect/sdk-sidewalk:main
      options: --cpus 2 --privileged
      volumes:
        - /hw_settings/hardware_map.yaml:/hw_settings/hardware_map.yaml
        - /dev:/dev
        - /run/udev:/run/udev
    defaults:
      run:
        shell: nrfutil toolchain-manager launch --install-dir /root/ncs bash -- {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: sidewalk

      - name: Install Python dependencies
        run: |
          python3 -m pip install -r sidewalk/scripts/ci/requirements.txt

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: tests-dut-artifacts

      - name: Run Tests
        run: |
          source /workdir/zephyr/zephyr-env.sh
          connected_DKs=`grep "connected: true" /hw_settings/hardware_map.yaml | wc -l`
          python3 sidewalk/scripts/ci/combine_twister_reports.py subsets/**/twister.json twister-out/twister.json
          python3 sidewalk/scripts/ci/combine_twister_reports.py subsets/**/testplan.json twister-out/testplan.json
          west twister -j $connected_DKs --no-clean -vvv --inline-logs --test-only --hardware-map /hw_settings/hardware_map.yaml --device-testing -T sidewalk/tests --retry-failed 2 --west-flash="--recover,--erase"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-dut_result
          path: |
            twister-out/twister.xml
            twister-out/**/handler.log
            twister-out/**/device.log

  build_and_run_ut_x86:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nrfconnect/sdk-sidewalk:main
      options: --cpus 2
    defaults:
      run:
        shell: nrfutil toolchain-manager launch --install-dir /root/ncs bash -- {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python dependencies
        run: |
          python3 -m pip install -r scripts/ci/requirements.txt

      - name: change_nrf_revision
        if: ${{ inputs.change_nrf_revision }}
        run: |
          python3 scripts/ci/replace_nrf_revision_in_west.py internal_west.yml

      - name: Reconfigure west
        run: |
          source /workdir/zephyr/zephyr-env.sh
          cp -r ../sdk-sidewalk /workdir/internal_sidewalk
          cd /workdir
          west config manifest.path internal_sidewalk && \
          west config manifest.file internal_west.yml && \
          west update --narrow -o=--depth=1 && \
          ln -s internal_sidewalk sidewalk

      - name: Build test artifacts for
        run: |
          source /workdir/zephyr/zephyr-env.sh
          west twister --platform native_posix --platform unit_testing --coverage --enable-ubsan --enable-lsan --enable-asan --testsuite-root /workdir/sidewalk/tests/ --inline-logs --overflow-as-errors -vvv

      - name: Fix coverage report
        run: |
          lcov -q --remove "twister-out/coverage.info" '/**/twister-out/*' '/**/mbedtls/*' '/**/test/cmock/*' '/**/zephyr/*' -o "coverage.info"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-x86_result
          path: |
            twister-out/twister.xml
            twister-out/**/handler.log
            twister-out/**/device.log

      - name: Upload Coverage report
        run: |
          echo "# Coverage" >> summary
          echo "" >> summary
          echo "## Summary" >> summary
          echo "" >> summary
          echo "\`\`\`" >> summary
          lcov --summary coverage.info >> summary
          echo "\`\`\`" >> summary
          echo "## File coverage" >> summary
          echp "">> summary
          echo "\`\`\`" >> summary
          lcov --list coverage.info >> summary
          echo "\`\`\`" >> summary
          cat summary >> $GITHUB_STEP_SUMMARY
