name: Run UT on boards
on:
  workflow_call:

jobs:
  run_tests_on_x86:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reconfigure west
        run: |
          cp -r ../sdk-sidewalk /workdir/sidewalk
          cd /workdir
          west config manifest.path sidewalk
          west update --narrow -o=--depth=1

      - uses: actions/download-artifact@v3
        with:
          name: tests-x86
          path: twister-out

      - name: Run Tests
        run: |
          chmod +x -R twister-out
          /workdir/zephyr/scripts/twister -vvv --inline-logs --test-only --platform native_posix --platform unit_testing -T /workdir/sidewalk/tests --retry-failed 2

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-x86_result
          path: |
            twister-out/twister.xml
            twister-out/**/handler.log
            twister-out/**/device.log


  run_tests_on_dut:
    runs-on: self-hosted
    steps:
      - name: Initial setup
        run: |
          echo "/home/sidewalk/.local/bin" >> $GITHUB_PATH
          echo "/usr/local/sbin" >> $GITHUB_PATH
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "/usr/sbin" >> $GITHUB_PATH
          echo "/usr/bin" >> $GITHUB_PATH
          echo "/sbin" >> $GITHUB_PATH
          echo "/bin" >> $GITHUB_PATH
          echo "/usr/share" >> $GITHUB_PATH
          echo "/snap/bin" >> $GITHUB_PATH
          rm -rf sidewalk artifacts twister-out* .west

      - name: Restart USB
        run: |
          numbers=`usbreset | grep J-Link | awk '{print $2}'`
          for number in $numbers
          do
            sudo usbreset $number
          done

      - uses: actions/checkout@v3
        with:
          path: sidewalk

      - name: Update nrf
        run: |
          west init -l sidewalk
          west update --narrow -o=--depth=1
          python3 -m pip install -r zephyr/scripts/requirements.txt

      - uses: actions/download-artifact@v3
        with:
          name: tests-dut-artifacts
          path: twister-out.tar.gz

      - name: Run Tests
        run: |
          tar -xzvf twister-out.tar.gz
          zephyr/scripts/twister --dry-run -P unit_testing -P native_posix -T sidewalk/tests --filter runnable -n
          mv twister-out/testplan.json twister-out/twister.json
          zephyr/scripts/twister -vvv --inline-logs --test-only --hardware-map /hw_settings/hardware_map.yaml --device-testing -T sidewalk/tests --west-flash="--recover,--erase"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-DUT_result
          path: |
            twister-out/twister.xml
            twister-out/**/handler.log
            twister-out/**/device.log

      - name: Cleanup
        if: always()
        run: |
          rm -rf sidewalk artifacts twister-out* .west
