name: Publish release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build_samples:
    uses: ./.github/workflows/samples_build.yml

  build_documentation:
    needs: [build_samples]
    uses: ./.github/workflows/publish_documentation.yml
    with:
      documentation_tag: ${{ github.event_name }}
      publish_to_prod: true
      publish_to_dev: true

  publish_release:
    needs: [build_documentation, build_samples]
    permissions: write-all
    name: Create release page
    runs-on: ubuntu-24.04

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+.[0-9]+.[0-9]+$ ]]; then
              echo "prerelease=false" >> $GITHUB_OUTPUT
          else
              echo "prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: prepare artifacts
        run: |
          mkdir package
          cd artifacts
          shopt -s extglob
          for f in !(*.zip) ; do zip -r $f.zip $f/; mv $f.zip ../package; done

      - name: Upload artifacts to release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: package/*.zip
          file_glob: true
          overwrite: true
          prerelease: ${{ steps.check-tag.outputs.prerelease }}
