name: Publish release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build_samples_and_tests:
    uses: ./.github/workflows/common-build.yml

  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build documentation
        run: cd doc; pip install -r requirements-doc.txt && sphinx-build -M html . build && zip -r documentation.zip build/html/*

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation.zip
          path: |
            doc/documentation.zip

  publish_release:
    needs: [build_documentation, build_samples_and_tests]
    permissions: write-all
    name: Create release page
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+.[0-9]+.[0-9]$ ]]; then
              echo "prerelease=false" >> $GITHUB_OUTPUT
          else
              echo "prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload documentation to release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/documentation.zip
          asset_name: documentation.zip
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ steps.check-tag.outputs.prerelease }}

      - name: Upload build binaries to release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/sample-artifacts
          asset_name: sample-artifacts.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ steps.check-tag.outputs.prerelease }}

      - name: Upload test-dut binaries to release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/tests-dut-artifacts
          asset_name: tests-dut-artifacts.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ steps.check-tag.outputs.prerelease }}

      - name: Upload test-dut binaries to release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/tests-manual-artifacts
          asset_name: tests-manual-artifacts.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ steps.check-tag.outputs.prerelease }}
