name: verify new ncs version

# The docker images are build at midnight, lets give it some time to build, and update in nordicplayground
on:
  schedule:
    - cron: "0 1 * * 1-6"

jobs:
  build_samples_and_tests:
    uses: nrfconnect/sdk-sidewalk/.github/workflows/common-build.yml@main
    with:
      change_nrf_revision: true
